// AUTO-GENERATED by kalayaan — do not edit; regenerated on every `kalayaan dev`/`deploy`.
import userConfig from "./config.generated.mjs";
import { resolveConfig, snapshotOf, createApp } from "kalayaan";
import plugins from "./plugins.generated.mjs";

const resolved = resolveConfig(userConfig);
const snapshot = snapshotOf(resolved);
const app = createApp(resolved, snapshot, { plugins });

export default {
  fetch: (request, env, ctx) => app.fetch(request, env, ctx),
};
