/**
 * The generated Worker entry. It's a plain ESM file, not magic: it imports
 * the CLI-generated pure-data config module (relative path) plus
 * resolveConfig/snapshotOf/createApp from the "kalayaan" umbrella package —
 * never from @kalayaan/config or @kalayaan/runtime directly, since a project
 * only ever declares "kalayaan" as a dependency, and package managers with
 * strict, non-hoisted resolution (pnpm workspaces in particular) won't
 * resolve a bare import of a transitive dependency that isn't re-exported
 * through something the project actually depends on (see
 * packages/kalayaan/src/index.ts). Config changes always require a
 * rebuild/redeploy since the Worker can't read cms.config.ts off disk at
 * request time.
 */
export function generateEntrySource(
  configImportPath: string,
  adapter = "d1",
  pluginsImportPath?: string,
  modulesImportPath?: string,
): string {
  // Only Postgres/MySQL projects import an external adapter factory (from the
  // `kalayaan/postgres`|`/mysql` subpaths). A D1 project imports nothing extra,
  // so its bundle never references the external drivers.
  const external =
    adapter === "postgres"
      ? { subpath: "kalayaan/postgres", symbol: "postgresAdapter" }
      : adapter === "mysql"
        ? { subpath: "kalayaan/mysql", symbol: "mysqlAdapter" }
        : null;

  const externalImport = external ? `import { ${external.symbol} } from ${JSON.stringify(external.subpath)};\n` : "";
  const pluginsImport = pluginsImportPath ? `import plugins from ${JSON.stringify(pluginsImportPath)};\n` : "";
  // Modules' collections were already merged into config.generated.mjs by the
  // CLI's loadConfig (see config-loader.ts) — this import brings in only their
  // runtime half (routes/hooks/fieldTypes/provides), registered alongside
  // plugins via createApp's `modules` option.
  const modulesImport = modulesImportPath ? `import modules from ${JSON.stringify(modulesImportPath)};\n` : "";
  // Assemble createApp options only when there's something to pass.
  const optionParts = [
    ...(external ? [`databaseAdapter: ${external.symbol}`] : []),
    ...(pluginsImportPath ? [`plugins`] : []),
    ...(modulesImportPath ? [`modules`] : []),
  ];
  const createAppCall = optionParts.length
    ? `createApp(resolved, snapshot, { ${optionParts.join(", ")} })`
    : `createApp(resolved, snapshot)`;
  // resolveConfig re-validates roles on every cold start (it's also the source
  // of ResolvedConfig, not just a build-time check) — so a role granting a
  // plugin- or module-declared custom subject (e.g. "marketplace:order") needs
  // that subject threaded through here too, or the deployed Worker would 500
  // on every request. See @kalayaan/config's ResolveConfigOptions.
  const needsPluginHost = Boolean(pluginsImportPath || modulesImportPath);
  const kalayaanImports = ["resolveConfig", "snapshotOf", "createApp", ...(needsPluginHost ? ["PluginHost"] : [])];
  const hostArrayExpr =
    pluginsImportPath && modulesImportPath
      ? "[...plugins, ...modules]"
      : pluginsImportPath
        ? "plugins"
        : modulesImportPath
          ? "modules"
          : "[]";
  const resolveConfigCall = needsPluginHost
    ? `resolveConfig(userConfig, { extraSubjects: new PluginHost(${hostArrayExpr}).subjects() })`
    : "resolveConfig(userConfig)";

  return `// AUTO-GENERATED by kalayaan — do not edit; regenerated on every \`kalayaan dev\`/\`deploy\`.
import userConfig from ${JSON.stringify(configImportPath)};
import { ${kalayaanImports.join(", ")} } from "kalayaan";
${externalImport}${pluginsImport}${modulesImport}
const resolved = ${resolveConfigCall};
const snapshot = snapshotOf(resolved);
const app = ${createAppCall};

export default {
  fetch: (request, env, ctx) => app.fetch(request, env, ctx),
};
`;
}
